-d C:\Users\Ben\Documents\GitHub\VZ300-on-a-tang9k\impl\gwsynthesis\HDMI_IP_Test.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\Ben\Documents\GitHub\VZ300-on-a-tang9k\src\HDMI_IP_Test.cst
-cfg C:\Users\Ben\Documents\GitHub\VZ300-on-a-tang9k\impl\pnr\device.cfg
-sdc C:\Users\Ben\Documents\GitHub\VZ300-on-a-tang9k\src\HDMI_IP_Test.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
